captainVersion: 4
services:
    # Directus
    $$cap_appname:
        image: directus/directus:$$cap_directus_tag
        volumes:
            - $$cap_appname-uploads:/directus/uploads
            - $$cap_appname-extensions:/directus/extensions
        restart: always
        environment:
            KEY: $$cap_directus_auth_public_key
            SECRET: $$cap_directus_auth_secret_key
            DB_CLIENT: 'pg'
            DB_HOST: $$cap_postgres_host
            DB_PORT: '5432'
            DB_DATABASE: $$cap_postgres_database_name
            DB_USER: $$cap_postgres_user
            DB_PASSWORD: $$cap_postgres_passwd
            DB_POOL__MIN: $$cap_db_pool_min
            DB_POOL__IDLE_TIMEOUT_MILLIS: $$cap_db_pool_idle_timeout_millis
            CACHE_ENABLED: $$cap_cache_enabled
            CACHE_STORE: 'redis'
            REDIS_HOST: $$cap_redis_host
            REDIS_PASSWORD: $$cap_redis_password
            REDIS_PORT: $$cap_redis_port
            ADMIN_EMAIL: $$cap_admin_email
            ADMIN_PASSWORD: $$cap_admin_password
            EMAIL_FROM: $$cap_email_from
            EMAIL_TRANSPORT: 'smtp'
            EMAIL_SMTP_HOST: $$cap_email_smtp_host
            EMAIL_SMTP_PORT: $$cap_email_smtp_port
            EMAIL_SMTP_USER: $$cap_email_smtp_user
            EMAIL_SMTP_PASSWORD: $$cap_email_smtp_password
            EMAIL_SMTP_SECURE: $$cap_email_smtp_secure
        caproverExtra:
            containerHttpPort: '8055'
caproverOneClickApp:
    variables:
        - description: Tag of Directus image on https://hub.docker.com/r/directus/directus/tags
          defaultValue: 11.6.1
          id: $$cap_directus_tag
          label: Directus image tag
          validRegex: /.{1,}/
        - description: Host of the Directus database instance.
          id: $$cap_postgres_host
          label: Postgres host
          defaultValue: database:5432
        - description: Name of the Directus database instance.
          defaultValue: directus
          id: $$cap_postgres_database_name
          label: Postgres database name
          validRegex: /.{1,}/
        - description: User for the Directus database instance.
          defaultValue: directus
          id: $$cap_postgres_user
          label: Postgres user
          validRegex: /.{1,}/
        - description: User password for the Directus database instance.
          defaultValue: $$cap_gen_random_hex(16)
          id: $$cap_postgres_passwd
          label: Postgres user password
          validRegex: /^(?=.*\d).{10,}$/
        - description: Minimum number of database connections in the pool.
          defaultValue: 0
          id: $$cap_db_pool_min
          label: Database pool min
          validRegex: /^\d+$/
        - description: Maximum number of milliseconds a connection can be idle before being released.
          defaultValue: 3000
          id: $$cap_db_pool_idle_timeout_millis
          label: Database pool idle timeout millis
          validRegex: /^\d+$/
        - description: Directus Auth Secret Key (must not be the same as Directus Auth Public Key)
          defaultValue: $$cap_gen_random_hex(16)
          id: $$cap_directus_auth_secret_key
          label: Directus Auth Secret Key
          validRegex: /^(?=.*\d).{10,}$/
        - description: Directus Auth Public Key (must not be the same as Directus Auth Secret Key)
          defaultValue: $$cap_gen_random_hex(16)
          id: $$cap_directus_auth_public_key
          label: Directus Auth Public Key
          validRegex: /^(?=.*\d).{10,}$/
        - description: Directus admin user email
          defaultValue: admin@example.com
          id: $$cap_admin_email
          label: Directus admin user email
          validRegex: /.{1,}/
        - description: Directus admin user password
          defaultValue: $$cap_gen_random_hex(8)
          id: $$cap_admin_password
          label: Directus admin user password
          validRegex: /^(?=.*\d).{8,}$/
        - description: Cache enabled
          id: $$cap_cache_enabled
          label: Cache enabled
          defaultValue: true
          validRegex: /^(true|false)$/
        - description: Cache store
          id: $$cap_cache_store
          label: Cache store
          defaultValue: redis
          validRegex: /.{1,}/
        - description: Host of the Directus database instance.
          id: $$cap_redis_host
          label: Redis host
          defaultValue: redis
        - description: Host of the Directus database instance.
          id: $$cap_redis_password
          label: Redis host
          defaultValue: redis
        - description: Host of the Directus database instance.
          id: $$cap_redis_port
          label: Redis host
          defaultValue: 6379
        - description: Email address from which emails are sent.
          id: $$cap_email_from
          label: Email from
          defaultValue: no-reply@example.com
          validRegex: /.{1,}/
        - description: SMTP host for sending emails.
          id: $$cap_email_smtp_host
          label: SMTP host
          defaultValue: smtp.example.com
          validRegex: /.{1,}/
        - description: SMTP port for sending emails.
          id: $$cap_email_smtp_port
          label: SMTP port
          defaultValue: 465
          validRegex: /^\d+$/
        - description: SMTP user for sending emails.
          id: $$cap_email_smtp_user
          label: SMTP user
          defaultValue: user@example.com
          validRegex: /.{1,}/
        - description: SMTP password for sending emails.
          id: $$cap_email_smtp_password
          label: SMTP password
          defaultValue: $$cap_gen_random_hex(16)
          validRegex: /^(?=.*\d).{10,}$/
        - description: SMTP secure for sending emails.
          id: $$cap_email_smtp_secure
          label: SMTP secure
          defaultValue: true
          validRegex: /^(true|false)$/
    instructions:
        end: >
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
        start: >-
            Directus is an open-source suite of software that wraps custom SQL databases with a dynamic API and intuitive Admin App.
            For more information and available options, see https://github.com/directus/docker or the official documentation at https://docs.directus.io
    displayName: 'Directus NoDB'
    isOfficial: true
    description: Directus is an open-source tool for managing content across all your omni-channel digital experiences
    documentation: Taken from https://docs.directus.io/guides/installation/docker/.
